### ISSUE TITLE
compiler issue

### ISSUE THREAD

**Issue by essnuked** [NethermindEth/zksync-remix-plugin#125]
After picking my environment ,compiling on my remix and compiling on zksync plugin, no compiled contract shows up to be deployed.

**Comment by stranger80** [comment]
Please note that at the moment the Remix plugin replicates exactly the functionality of Hardhat, ie. the source code must reside in `contracts` workspace folder. If your selected .sol file is outside of that folder, it will not be submitted for compilation.

Realizing this is potentially confusing, we are refactoring the UX to explicitly list two compilation options - #128

**Comment by satyambnsal** [comment]
Fixed as part of [0.4.2](https://github.com/NethermindEth/zksync-remix-plugin/releases/tag/v0.4.2) release.
