### ISSUE TITLE
Deploy tab showing No contracts ready for deployment yet.

### ISSUE THREAD

**Issue by Tariq-Imran** [NethermindEth/zksync-remix-plugin#138]
This is my first compile and deploy at ZKsync
Compile tab working properly with ZKsync plugin. but deploy tab showing No contracts ready for deployment yet, compile a solidity contract.
Compile and deploy working good with remix solidity compiler.

**Comment by varex83** [comment]
Hello @Tariq-Imran !

It seems like you put your contract file into the wrong directory. Our plugin reproduces the standard structure of hardhat project, so all of your contracts should be in the contracts directory, or they won't be compiled. While our team is working on providing better interface, you can just create contracts directory and put your contracts there, and try compiling it again.

Let me know if it helped you!

**Comment by Tariq-Imran** [comment]
Thanks for your help.
It's working perfectly.
