### ISSUE TITLE
Add CI for check linting on UI side 

### ISSUE THREAD

**Issue by varex83** [NethermindEth/zksync-remix-plugin#142]

**Comment by 0xmihirsahu** [comment]
I'd like to work on this issue. Can you provide more details?

**Comment by varex83** [comment]
Hey @0xmihirsahu ! Sure, feel free to ask any questions!

**Comment by varex83** [comment]
@0xmihirsahu extra info: we have `lint` script in our `package.json`, which we want to trigger on every PR

**Comment by 0xmihirsahu** [comment]
@varex83 so I have to setup github actions for that right?

**Comment by 0xmihirsahu** [comment]
#145
