### ISSUE TITLE
Plugin crashes after switching between two contracts in the "Interact" tab

### ISSUE THREAD

**Issue by varex83** [NethermindEth/zksync-remix-plugin#186]
Steps to reproduce:

- Enable ZKsync plugin in the Remix
- Create a new project by cloning this repo: https://github.com/matter-labs/custom-paymaster-tutorial
- Compile and deploy ERC20 token.
- Compile and deploy paymaster.
- In the "interact" tab, switch between deployed contracts.

Video to demonstrate the bug: https://www.loom.com/share/2c959c9e385a49cb87bb268d3b2e152d

**Comment by shah-aman** [comment]
@varex83  is it still open in todo or assigned to @ashleendaly  . i would like to take this

**Comment by ashddev** [comment]
@shah-aman I am working on this
