### ISSUE TITLE
Remove Unused ECS Clusters to Eliminate on Prod and Dev Accounts

### ISSUE THREAD

**Issue by varex83** [NethermindEth/zksync-remix-plugin#189]
We have unused ecs clusters running both on prod and dev accounts so as far, as we found out:
- For prod we use only **(prod)**: [zksync-remix-plugin-prod-ecs-cluster ](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/zksync-remix-plugin-prod-ecs-cluster?region=us-east-2)
- For dev **(staging)**: [zksync-remix-plugin-dev-ecs-cluster](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/zksync-remix-plugin-dev-ecs-cluster/services?region=us-east-2)

All other clusters should be removed, since we aren't using them: 
- [new-zksync-remix-ecs-cluster (dev)](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/new-zksync-remix-ecs-cluster?region=us-east-2) - **DONE**;
- [zksync-remix-plugin-ecs-cluster (dev)](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/zksync-remix-plugin-ecs-cluster?region=us-east-2)  - **DONE**;

**Comment by ghost** [comment]
The ECS clusters new-zksync-remix-ecs-cluster and zksync-remix-plugin-ecs-cluster have been successfully deleted.
