### ISSUE TITLE
URGENT Clarify the situation with zkSync backend and sort the URLs!

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/zksync-remix-plugin#207]
There are now two zksync related clusters in nubia-shared-prod:

1. [zksync-remix-plugin-production-ecs-cluster](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/zksync-remix-plugin-production-ecs-cluster?region=us-east-2) 
2. [zksync-remix-plugin-prod-ecs-cluster](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/zksync-remix-plugin-prod-ecs-cluster?region=us-east-2)

There is currently `https://zksync-plugin-api.nethermind.io/` which is pointing to `zksync-remix-plugin-production-ecs-cluster` - this is WRONG. This URL should point to `zksync-remix-plugin-prod-ecs-cluster`. The same aplies to `
https://zksync-devnet.nethermind`

ACTION REQUIRED:
- SORT the URLs https://zksync-plugin-api.nethermind.io and https://zksync-devnet.nethermind to point to the correct cluster `zksync-remix-plugin-prod-ecs-cluster` - **DONE**;
- REMOVE `zksync-remix-plugin-production-ecs-cluster` cluster -  **DONE**;

**Comment by colintuam** [comment]
Hi @stranger80 

Both `zksync-plugin-api.nethermind.io` and `zksync-devnet.nethermind.io` are now pointing to the ALB for the [zksync-remix-plugin-prod-ecs-cluster](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/zksync-remix-plugin-prod-ecs-cluster?region=us-east-2) cluster  `zksync-remix-prod-alb-2136581647.us-east-2.elb.amazonaws.com`

I edited the two ALB listener rules to allow the forwarding of traffic to the container instances. Previously they only had rules for `zksync-devnet-test` and `zksync-plugin-api-test`

I will touch base with @dnnthm in relation to the terraform for the [zksync-remix-plugin-production-ecs-cluster](https://us-east-2.console.aws.amazon.com/ecs/v2/clusters/zksync-remix-plugin-production-ecs-cluster?region=us-east-2) cluster with a view to removing this today

**Comment by ghost** [comment]
Hi @colintuam, the `zksync-remix-plugin-prod-ecs-cluster` is being added in [PR #48](https://github.com/NethermindEth/terragrunt/pull/48), which is currently under review and may still be modified. I've initiated a thread to address the remaining points [here](https://demerzelsolutions.slack.com/archives/C04PZV3T9NF/p1727167104905479).

### Recommended Order of Actions:

1. Get merged/fully applied the above PR - **DONE**;
2. Conduct testing by the developer -  **DONE**;
3. If testing is successful, update Cloudflare records to point to zksync-remix-plugin-prod-ecs-cluster  -  **DONE**;
4. After switching, validate that zksync-remix-plugin-production-ecs-cluster is no longer in use.  - **DONE**;
5. Delete zksync-remix-plugin-production-ecs-cluster and its components.  - **DONE**;
6. Developer to perform a final validation post-removal to ensure no issues are present. - **DONE**.

@stranger80 I noticed you marked the priority as URGENT. Could you please clarify the business or technical impact to ensure we can prioritize it appropriately?

**Comment by colintuam** [comment]
I have repointed the domains back to the original ALB pending the tests/verification from @varex83

**Comment by stranger80** [comment]
Tests on zksync-plugin-api-test.nethermind.io and zksync-devnet-test.nethermind.io completed successfully Please proceed with DNS record updates for https://zksync-plugin-api.nethermind.io/ and https://zksync-devnet.nethermind/ to point to the correct cluster zksync-remix-plugin-prod-ecs-cluster

(Tests performed after updating the hosts file to point the prod URLs to the new cluster locally, and running Remix plugin from Mozilla: )
![image](https://github.com/user-attachments/assets/05db7e1d-fa90-4a6c-8493-b636b13ffc6b)
