### ISSUE TITLE
Fix API Server log configuration

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/zksync-remix-plugin#212]
The current API Server when deployed into ECS cluster is generating overwhelmingly large (and useless) volume of logs. It seems that logs as recorded by ECS (which are directly fetched from container console) ignore the RUST_LOG=INFO - the CloudWatch logs are littered with tons of TRACE and DEBUG records.

**Comment by taco-paco** [comment]
Could we solve this in refactoring? The amount of logs shall be decreased significantly

**Comment by stranger80** [comment]
...but right now the volume is killing us and makes troubleshooting really painful.
