### ISSUE TITLE
[zkSync Remix plugin, nubia-shared-staging] Downsize API backend container. Fix secret management approach.

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/zksync-remix-plugin#233]
1. [DevOps] Create a secret in `nubia-shared-staging` account under name: 
`arn:aws:secretsmanager:us-east-2:599564732950:secret:zksync-remix-plugin-promtail-password-WTETsu:promtail_password::`
Clone the following secret from `nubia-shared-prod` account:
`arn:aws:secretsmanager:us-east-2:228016254426:secret:zksync-remix-plugin-promtail-password-WTETsu:promtail_password::` - new [secret](https://us-east-2.console.aws.amazon.com/secretsmanager/secret?name=zksync-remix-plugin-promtail-password&region=us-east-2) has been created - `zksync-remix-plugin-promtail-password` - **DONE**

3. [DevOps] Apply Terraform changes in PR:  https://github.com/NethermindEth/terragrunt/pull/109
4. Amend Dev instance Deployment flow to NOT populate `PROMTAIL_PASSWORD` env variable.
5. Deploy to the Dev plugin instance to confirm.

**Comment by ghost** [comment]
Verification of the changes in the dev environment has been confirmed as per [thread](https://demerzelsolutions.slack.com/archives/C02JYAUN0PL/p1729502900068829?thread_ts=1729256762.353539&cid=C02JYAUN0PL).
