### ISSUE TITLE
Implement robust devnet backend instead of the simple "in-memory" setup

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/zksync-remix-plugin#56]
Instead of in-memory devnet backend, implement a test backend following the simple architecture illustrated here: 
https://github.com/matter-labs/local-setup/blob/main/docker-compose.yml

**Comment by MexicanAce** [comment]
Here's a more defined document on the Docker setup : https://era.zksync.io/docs/tools/testing/dockerized-testing.html

**Comment by MexicanAce** [comment]
Just run `npx zksync-cli dev start` if you want to simplify it the most

**Comment by stranger80** [comment]
> Just run `npx zksync-cli dev start` if you want to simplify it the most

Hmmm, not sure if that would help us, as it uses docker compose under the hood, right? 
As docker-compose is not intended for production use, in prod environment we need to define 3 managed containers.
