### ISSUE TITLE
Cache issue with updating to new version

### ISSUE THREAD

**Issue by olehbairak** [NethermindEth/zksync-remix-plugin#64]
Currently, we spotted on production environment that in order to apply/use new version of the Remix zkSync plugin user have to **clean browser cache** otherwise he will use the previously used version.
Might be two steps to resolving the issue:

_Fast one:_ 
Make a warning message each new release, that there were a new version deployed - please make sure that you cleaned your cache and proper version is displayed in version of Plugin section.

_More fundamental fix:_
Make new version automatically applied on the prod instance.

**Comment by varex83** [comment]
Added the information about version matching between UI and API

Now, while deploying, the version of service is set on the back-end side as env variable, and also it sets as package version in package.json of UI service. In the runtime it checks if version of client is greater or equal than version of back-end, if yes it just informs about using the latest UI version, if not it suggest cleaning up the cache and force-reloading the plugin
