### ISSUE TITLE
Issue with Seplia network integration connected to browser cache

### ISSUE THREAD

**Issue by olehbairak** [NethermindEth/zksync-remix-plugin#66]
During testing new version `Plugin version: v0.1.2-dev12` it was spotted that in the cache old network config conflicts with new Sepolia setup.
As a result if user won't clean the cache - deployment of the contract in Remix zkSync plugin will lead to a console error stating that there's wrong network config for Sepolua network. (apperently in the cache there's an old one connected to Goerli network).
STR:

1. Open Remix zkSync plugin 
2. Compile and deploy any contract 

Expected result: Contracts should be deployed without error.
Actual result: Console error is present and contract can't be deployed.

Console error text:
Error: {"reason":"underlying network changed","code":"NETWORK_ERROR","event":"changed","network":{"chainId":280,"name":"zkSync Era Testnet"},"detectedNetwork":{"chainId":300,"name":"unknown"}}

**Comment by varex83** [comment]
It shouldn't be the problem after cache cleaning, that should be only once after the sepolia support release,
but also this should be fixed in #64
