### ISSUE TITLE
Implement contract verification via plugin

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/zksync-remix-plugin#77]
Add feature to seamlessly submit a deployed contract for verification (see https://docs.zksync.io/build/tooling/block-explorer/contract-verification.html#hardhat-plugin )

**Comment by stranger80** [comment]
Note after demo with Ago:
- Consider pre-populating the Contract Address control with the address of the most recently deployed smart contract

**Comment by agolajko** [comment]
Fix 'contract verification successful' message on terminal which is being presented even when unsuccesful

**Comment by agolajko** [comment]
Change the contract verification process to one where it's an opt-in:

- "remove the standalone verification option and keep it only on deployment as optional"
- Include the inputs used for the deployment as the same inputs for the verification
- also, if the checkbox is checked, the button should read "Deploy and verify"
- Fix 'contract verification successful' message on terminal which is being presented even when unsuccesful


![image](https://github.com/NethermindEth/zksync-remix-plugin/assets/57454127/26c3541b-221c-46ef-8a09-0204a5b275b9)

**Comment by pauliax** [comment]
Afaik plugin now supports deploy and verification:
https://github.com/NethermindEth/zksync-remix-plugin/pull/91

I have previously deployed a contract when this feature was not available. Would it be possible to add verification for an already deployed contract?

**Comment by varex83** [comment]
Hey @pauliax ! Sorry for the late response, I've totally missed your message! Yes, of course we are thinking on the adding this kind of functinoallity. I will create an issue for that in order to track it!
