### ISSUE TITLE
Outdated version of zkSync Plugin

### ISSUE THREAD

**Issue by bxpana** [NethermindEth/zksync-remix-plugin#84]
When using the zkSync plugin you get `You are using an outdated version of the zkSync plugin: v0.1.2-27, please update to v0.1.2-30 by force-refreshing the page and clearing your browser cache.`

Clearing the browser cache and force-refreshing does not update the plugin. 

Can you please make sure to update the plugin so it works correctly on Remix?

**Comment by varex83** [comment]
Related to https://github.com/NethermindEth/zksync-remix-plugin/issues/126
